"""
Dictionaries to group diagnoses into more general illnesses
"""


dict_laura_roman = {
    "enfermedades_la_boca_lengua_labios": "Diagnósticos de boca",
    "signos_sintomas_boca_lengua_y_labios": "Diagnósticos de boca",
    "signos_sintomas_dientes_y_encias": "Diagnósticos de boca",
    "enfermedades_los_dientes_encias": "Diagnósticos de boca",
    "mastopatia_fibroquistica": "Tumores gine benignos",
    "fibromioma_uterino": "Tumores gine benignos",
    "neoplasia_benigna_ovario": "Tumores gine benignos",
    "neoplasia_benigna_la_mama": "Tumores gine benignos",
    "otras_neoplasias_benignas_del_utero": "Tumores gine benignos",
    "neoplasias_benignas_del_aparato_genital_femenino": "Tumores gine benignos",
    "enteritis_cronica_colitis_ulcerosa": "Síntomas del digestivo bajo",
    "estrenimiento": "Síntomas del digestivo bajo",
    "incontinencia_fecal": "Síntomas del digestivo bajo",
    "flatulencia_aerofagia_dolor_por_gases": "Síntomas del digestivo bajo",
    "melena": "Síntomas del digestivo bajo",
    "sindrome_colon_irritable": "Síntomas del digestivo bajo",
    "fisura_anal_absceso_perianal": "Síntomas del digestivo bajo",
    "cambio_en_las_heces_en_el_ritmo_intestinal": "Síntomas del digestivo bajo",
    "dolor_rectal_anal": "Síntomas del digestivo bajo",
    "diarrea": "Síntomas del digestivo bajo",
    "enfermedad_diverticular_del_intestino": "Síntomas del digestivo bajo",
    "otros_signos_sintomas_del_aparato_digestivo": "Síntomas del digestivo bajo",
    "otras_enfermedades_del_aparato_digestivo": "Síntomas del digestivo bajo",
    "incapacidad_minusvalia_del_aparato_digestivo": "Síntomas del digestivo bajo",
    "enfermedad_celiaca": "Síntomas del digestivo bajo",
    "rectorragia_hemorragia_rectal": "Síntomas del digestivo bajo",
    "flamatorios_ovario_trompa_falopio_y_ligamento_ancho": "Trastornos no inflamatorios ginecología",
    "prolapso_uterovaginal.89": "Trastornos no inflamatorios ginecología",
    "prolapso_uterovaginal": "Trastornos no inflamatorios ginecología",
    "trastornos_no_inflamatorios_del_cervix": "Trastornos no inflamatorios ginecología",
    "otros_signos_sintomas_vulvares": "Trastornos no inflamatorios ginecología",
    "anomalias_congenitas_del_aparato_genital_femenino": "Trastornos no inflamatorios ginecología",
    "vaginitis_vulvitis_no_especificada": "Infecciones ginecológicas",
    "prurito_vulvar": "Infecciones ginecológicas",
    "candidiasis_genital_en_la_mujer": "Infecciones ginecológicas",
    "citologia_cuello_utero_anormal": "Infecciones ginecológicas",
    "frotis_papanicolaou_anormal_vagina_y_vph_vaginal": "Infecciones ginecológicas",
    "alteracion_la_menstruacion_hemorragia": "Diagnósticos menstruación",
    "signos_sintomas_menopausicos": "Diagnósticos menstruación",
    "endometriosis": "Diagnósticos menstruación",
    "sindrome_premenstrual": "Diagnósticos menstruación",
    "enfermedad_inflamatoria_pelvica": "Diagnósticos menstruación",
    "infeccion_intestinal_inespecifica_posible": "Infección digestivo",
    "parotiditis_epidemica_paperas": "Infección digestivo",
    "infeccion_gastrointestinal": "Infección digestivo",
    "apendicitis": "Infección digestivo",
    "prurito_perianal": "Infección digestivo",
    "equinococosis_hidatidosis": "Infección digestivo",
    "hepatomegalia": "Diagnósticos hepáticos",
    "hepatoesplenomegalia_no_incluida_en_b87_o_d23": "Diagnósticos hepáticos",
    "hepatitis_viral": "Diagnósticos hepáticos",
    "colecistitis_colelitiasis": "Diagnósticos hepáticos",
    "ictericia": "Diagnósticos hepáticos",
    "hematemesis_vomito_sangre": "Diagnósticos hepáticos",
    "otros_dolores_abdominales_localizados.83": "otros_dolores_abdominales_localizados",
    "otros_dolores_abdominales_localizados.826": "otros_dolores_abdominales_localizados",
    "otros_dolores_abdominales_localizados": "otros_dolores_abdominales_localizados",
    "pirosis": "Diagnósticos digestivo alto",
    "problemas_la_deglucion": "Diagnósticos digestivo alto",
    "enfermedades_del_esofago": "Diagnósticos digestivo alto",
    "vomito": "Diagnósticos digestivo alto",
    "alteraciones_funcionales_del_estomago": "Diagnósticos digestivo alto",
    "dispepsia_indigestion": "Diagnósticos digestivo alto",
    "otras_ulceras_pepticas": "Diagnósticos digestivo alto",
    "dolor_abdominal": "Diagnósticos digestivo alto",
    "nausea_y_vomito": "Diagnósticos digestivo alto",
    "ulcera_duodenal": "Diagnósticos digestivo alto",
    "hernia_inguinal": "Masas del sistema digestivo",
    "masa_abdominal_no_especificada": "Masas del sistema digestivo",
    "otras_hernias_abdominales_": "Masas del sistema digestivo",
    "hernia_hiato": "Masas del sistema digestivo",
    "cuerpo_extrano_en_tracto_digestivo": "Masas del sistema digestivo",
    "persona_que_finge_enfermedad": "finge_enfer",
    "persona_que_finge_enfermedad_simulacion_consciente": "finge_enfer",
}


##Dictionaries to group chronic pathologies into more general pathologies


dict_laura_roman_bps = {
    "vih": "Enfermedades infecciosas",
    "artrosis__espondilosis": "Afección osteomuscular",
    "osteoporosis": "Afección osteomuscular",
    "gota_y_otras_artropatias_por_cristales": "Afección osteomuscular",
    "otra_artropatía": "Afección osteomuscular",
    "artritis_reumatoiy_enfermedades_relacionadas": "Afección osteomuscular",
    "enfermedad_del_colageno_y_vasculitis": "Afección osteomuscular",
    "fibromialgia": "Afección osteomuscular",
    "cirrosis_hepatica": "Afección hepática",
    "esteatosis_hepatica": "Afección hepática",
    "hepatopatia_cronica_excepto_cirrosis": "Afección hepática",
    "enteritis_regional_y_colitis_ulcerosa": "Afección del sistema digestivo",
    "sindrome_malabsorcion_e_intolerancia_alimenticia": "Afección del sistema digestivo",
    "enfermedad_valvular_adquirida": "Afección cardíaca",
    "insuficiencia_cardiaca": "Afección cardíaca",
    "enfermedad_cerebrovascular_mal_definida_y_otra": "Afección cardíaca",
    "oclusion_o_estenosis_arterias_precerebrales": "Afección cardíaca",
    "secuela_enfermedad_cerebrovascular": "Afección cardíaca",
    "arteriopatia_extremidades": "Afección cardíaca",
    "arteriopatia_intraabdominal": "Afección cardíaca",
    "aneurisma_arterias_aorta__perifericas_y_viscerales": "Afección cardíaca",
    "anomalia_congenita_cardiaca_y_circulatoria": "Afección cardíaca",
    "epoc": "Afección respiratoria",
    "asma": "Afección respiratoria",
    "insuficiencia_renal_cronica": "Afección genitourinaria",
    "litineursis_urinaria": "Afección genitourinaria",
    "dermatitis_atopica": "Enfermedades de la piel",
    "psoriasis": "Enfermedades de la piel",
    "otro_trastorno_mental_organico": "Salud mental",
    "dependencia_alcohol": "Salud mental",
    "dependencia_tabaco": "Salud mental",
    "dependencia_otras_sustancias": "Salud mental",
    "trastorno_ansiedad": "Salud mental",
    "trastorno_estado_animo": "Salud mental",
    "trastorno_esquizofrenico": "Salud mental",
    "trastorno_inicio_infancia_adolescencia": "Salud mental",
    "trastorno_personalidad_y_comportamiento_adulto": "Salud mental",
    "otro_trastorno_funcional": "Salud mental",
    "trastorno_conducta_alimentaria": "Salud mental",
    "otro_trastorno_del_desarrollo": "Salud mental",
    "trastorno_del_espectro_autista": "Salud mental",
    "discapacidad_intelectual": "Salud mental",
    "diabetes": "Afecciones endocrinas",
    "dislipemia": "Afecciones endocrinas",
    "hipotiroidismo": "Afecciones endocrinas",
    "obesidad": "Afecciones endocrinas",
    "enfermedad_parkinson": "Afecciones del sistema nervioso",
    "enfermedad_neurologica_con_deficit_motor_no_acv": "Afecciones del sistema nervioso",
    "sindrome_extrapiramidal": "Afecciones del sistema nervioso",
    "epilepsia": "Afecciones del sistema nervioso",
    "leucemia": "Neoplasias hematológicas",
    "cancer_inmunoproliferativo": "Neoplasias hematológicas",
    "linfoma_no_hodgkin": "Neoplasias hematológicas",
    "enfermedad_hodgkin": "Neoplasias hematológicas",
    "cancer_colorrectal": "Neoplasias digestivo I",
    "cancer_higado_y_vias_biliares": "Neoplasias digestivo II",
    "cancer_pancreas": "Neoplasias digestivo II",
    "cancer_estomago": "Neoplasias digestivo II",
    "cancer_bronquio_y_pulmon": "Neoplasias de las vías respiratorias",
    "cancer_utero": "Cánceres ginecológicos",
    "cancer_cuello_uterino": "Cánceres ginecológicos",
    "cancer_cabeza_y_cuello": "Cánceres raros",
    "cancer_tiroides": "Cánceres raros",
    "cancer_hueso_y_tejidos_blandos": "Cánceres raros",
    "cancer_rinon_y_pelvis_renal": "Cánceres raros",
    "sarcoma_kaposi": "Cánceres raros",
    # ---------------------------------
}

# Ginecological cancers

gine_cancer = [
    "cancer_mama",
    "cancer_utero",
    "cancer_cuello_uterino",
    "cancer_de_utero",
    "cancer_de_cuello_uterino",
    "cancer_de_mama",
]

# Non-ginecological cancers

other_cancer = [
    "cancer_de_pancreas",
    "cancer_colorrectal",
    "cancer_de_prostata",
    "cancer_de_vejiga",
    "cancer_de_hueso_y_tejidos_blandos",
    "cancer_de_rinon_y_pelvis_renal",
    "cancer_de_cabeza_y_cuello",
    "linfoma_no_hodgkin",
    "enfermedad_de_hodgkin",
    "melanoma_de_piel",
    "cancer_de_higado_y_vias_biliares",
    "cancer_de_bronquio_y_pulmon",
    "cancer_de_tiroides",
    "cancer_inmunoproliferativo",
    "cancer_de_estomago",
    "cancer_de_testiculo",
    "cancer_pancreas",
    "cancer_colorrectal",
    "cancer_prostata",
    "cancer_vejiga",
    "cancer_hueso_y_tejidos_blandos",
    "cancer_rinon_y_pelvis_renal",
    "cancer_higado_y_vias_biliares",
    "cancer_bronquio_y_pulmon",
    "cancer_tiroides",
    "cancer_inmunoproliferativo",
    "cancer_estomago",
    "cancer_testiculo",
]


# Dictionary to transform from CIE9 to descriptive strings

mapping = {
    "617": "Endometriosis",
    "N80": "Endometriosis",
    "610": "Mastopatia_fibroquistica",
    "N60": "Neoplasia_benigna_de_la_mama",
    "625.4": "Sindrome_premenstrual",
    "N94.3": "Sindrome_premenstrual",
    "618": "Prolapso_uterovaginal",
    "N81": "Prolapso_uterovaginal",
    "616": "Vaginitis_vulvitis_no_especificada",
    "N77": "Vaginitis_vulvitis_no_especificada",
    "N76": "Vaginitis_vulvitis_no_especificada",
    "627": "Signos_sintomas_menopausicos",
    "N95": "Signos_sintomas_menopausicos",
    "626": "Alteracion_de_la_menstruacion_hemorragia",
    "N92": "Alteracion_de_la_menstruacion_hemorragia",
    "N93": "Alteracion_de_la_menstruacion_hemorragia",
    "698.1": "Prurito_vulvar",
    "L29.2": "Prurito_vulvar",
    "614": "Enfermedad_inflamatoria_pelvica",
    "N70": "Enfermedad_inflamatoria_pelvica",
    "N71": "Enfermedad_inflamatoria_pelvica",
    "N73": "Enfermedad_inflamatoria_pelvica",
    "112.1": "Candidiasis_genital_en_la_mujer",
    "B37.3": "Candidiasis_genital_en_la_mujer",
    "218": "Fibromioma_uterino",
    "D25": "Fibromioma_uterino",
    "221": "Neoplasias_benignas_del_aparato_genital_femenino",
    "D28": "Neoplasias_benignas_del_aparato_genital_femenino",
    "217": "Neoplasia_benigna_de_la_mama",
    "219": "Otras_neoplasias_benignas_del_utero",
    "D26": "Otras_neoplasias_benignas_del_utero",
    "220": "Neoplasia_benigna_ovario",
    "D27": "Neoplasia_benigna_ovario",
    "752": "Anomalias_congenitas_del_aparato_genital_femenino",
    "Q50": "Anomalias_congenitas_del_aparato_genital_femenino",
    "Q52": "Anomalias_congenitas_del_aparato_genital_femenino",
    "Q51": "Anomalias_congenitas_del_aparato_genital_femenino",
    "620": "Trastornos_no_inflamatorios_de_ovario_trompa_de_Falopio_y_ligamento_ancho",
    "N83": "Trastornos_no_inflamatorios_de_ovario_trompa_de_Falopio_y_ligamento_ancho",
    "795.0": "Frotis_de_Papanicolaou_anormal_de_vagina_y_VPH_vaginal",
    "R87.6": "Citologia_de_cuello_de_utero_anormal",
    "795.1": "Frotis_de_Papanicolaou_anormal_de_vagina_y_VPH_vaginal",
    "792.9": "Hallazgos_anormales_en_fluidos_vaginales",
    "R87.9": "Hallazgos_anormales_en_fluidos_vaginales",
    "787.1": "Pirosis",
    "R12": "Pirosis",
    "564.6": "Dolor_rectal_anal",
    "K59.4": "Dolor_rectal_anal",
    "698.0": "Prurito_perianal",
    "L29.0": "Prurito_perianal",
    "536.8": "Dispepsia_indigestion",
    "K30": "Dispepsia_indigestion",
    "787.3": "Flatulencia_aerofagia_dolor_por_gases",
    "R14": "Flatulencia_aerofagia_dolor_por_gases",
    "564.0": "Estrenimiento",
    "K56.4": "Estrenimiento",
    "782.4": "Ictericia",
    "R17": "Ictericia",
    "578.0": "Hematemesis_vomito_de_sangre",
    "K92.0": "Hematemesis_vomito_de_sangre",
    "578.1": "Melena",
    "K92.1": "Melena",
    "569.3": "Rectorragia_hemorragia_rectal",
    "K62.5": "Rectorragia_hemorragia_rectal",
    "787.6": "Incontinencia_fecal",
    "R15": "Incontinencia_fecal",
    "787.99": "Cambio_en_las_heces_en_el_ritmo_intestinal",
    "R19.4": "Cambio_en_las_heces_en_el_ritmo_intestinal",
    "520.7": "Signos_sintomas_de_dientes_y_encias",
    "K00.7": "Signos_sintomas_de_dientes_y_encias",
    "529.1": "Signos_sintomas_de_boca_lengua_y_labios",
    "K14.1": "Signos_sintomas_de_boca_lengua_y_labios",
    "787.2": "Problemas_de_la_deglucion",
    "R13": "Problemas_de_la_deglucion",
    "789.1": "Hepatomegalia",
    "R16.0": "Hepatomegalia",
    "789.3": "Masa_abdominal_no_especificada",
    "R19.0": "Masa_abdominal_no_especificada",
    "V55.1": "Incapacidad_minusvalia_del_aparato_digestivo",
    "Z43.1": "Incapacidad_minusvalia_del_aparato_digestivo",
    "789.5": "Otros_signos_sintomas_del_aparato_digestivo",
    "R18": "Otros_signos_sintomas_del_aparato_digestivo",
    "1": "Infeccion_gastrointestinal",
    "A00": "Infeccion_gastrointestinal",
    "72": "Parotiditis_epidemica_paperas",
    "B26": "Parotiditis_epidemica_paperas",
    "70": "Hepatitis_viral",
    "B15": "Hepatitis_viral",
    "5": "Infeccion_intestinal_inespecifica_posible",
    "A05": "Infeccion_intestinal_inespecifica_posible",
    "935": "Cuerpo_extrano_en_tracto_digestivo",
    "T18": "Cuerpo_extrano_en_tracto_digestivo",
    "528.9": "Otras_lesiones_del_aparato_digestivo",
    "K13.1": "Otras_lesiones_del_aparato_digestivo",
    "520": "Enfermedades_de_los_dientes_encias",
    "K00": "Enfermedades_de_los_dientes_encias",
    "528.1": "Enfermedades_de_la_boca_lengua_labios",
    "A69.0": "Enfermedades_de_la_boca_lengua_labios",
    "530.1": "Enfermedades_del_esofago",
    "K20": "Enfermedades_del_esofago",
    "532": "ulcera_duodenal",
    "K26": "ulcera_duodenal",
    "531": "Otras_ulceras_pepticas",
    "K25": "Otras_ulceras_pepticas",
    "535": "Alteraciones_funcionales_del_estomago",
    "K29": "Alteraciones_funcionales_del_estomago",
    "540": "Apendicitis",
    "K35": "Apendicitis",
    "550": "Hernia_inguinal",
    "K40": "Hernia_inguinal",
    "552": "Hernia_de_hiato",
    "K44": "Hernia_de_hiato",
    "553": "Otras_hernias_abdominales",
    "K41": "Otras_hernias_abdominales",
    "564.1": "Sindrome_de_colon_irritable",
    "K58": "Sindrome_de_colon_irritable",
    "555": "Enteritis_cronica_colitis_ulcerosa",
    "K50": "Enteritis_cronica_colitis_ulcerosa",
    "565": "Fisura_anal_absceso_perianal",
    "K60": "Fisura_anal_absceso_perianal",
    "120": "Oxiuros_ascaris_otros_parasitos",
    "B65": "Oxiuros_ascaris_otros_parasitos",
    "122": "Equinococosis_hidatidosis",
    "B67": "Equinococosis_hidatidosis",
    "130": "Enfermedades_hepaticas_no_especificadas",
    "B58.1": "Enfermedades_hepaticas_no_especificadas",
    "574": "Colecistitis_colelitiasis",
    "K80": "Colecistitis_colelitiasis",
    "078.5": "Otras_enfermedades_del_aparato_digestivo",
    "B25.2": "Otras_enfermedades_del_aparato_digestivo",
    "579.0": "Enfermedad_celiaca",
    "K90.0": "Enfermedad_celiaca",
    "N87": "Citologia_de_cuello_de_utero_anormal",
    "N86": "Citologia_de_cuello_de_utero_anormal",
    "R10": "Otros_dolores_abdominales_localizados",
    "R11": "Vomito",
    "K59.1": "Diarrea",
    "R16": "Hepatoesplenomegalia_no_incluida_en_B87_o_D23",
    "K00.0": "Anomalias_congenitas_del_aparato_digestivo",
    "K57": "Enfermedad_diverticular_del_intestino",
    "Z76.5": "Persona_que_finge_enfermedad_simulacion_consciente",
    "622": "Trastornos_no_inflamatorios_del_cervix",
    "562": "Diverticulos_intestinales",
    "V65.2": "Persona_que_finge_enfermedad",
    "789.0": "Dolor_abdominal",
    "787.0": "Nausea_y_vomito",
    "564.5": "Diarrea_funcional",
    "624": "Otros_signos_sintomas_vulvares",
}


dict_bps_english_no_group = {
    "Aneurisma arterias aorta, periféricas y viscerales": "Aneurysm of aorta, peripheral, and visceral arteries",
    "Anomalía congénita cardíaca y circulatoria": "Congenital heart and circulatory anomaly",
    "Arteriopatía de extremidades": "Limb arteriopathy",
    "Arteriopatía intraabdominal": "Intraabdominal arteriopathy",
    "Artritis reumatoide y enfermedades relacionadas": "Rheumatoid arthritis and related diseases",
    "Artrosis, espondilosis": "Osteoarthritis, spondylosis",
    "Asma": "Asthma",
    "Cardiopatía isquémica": "Ischemic heart disease",
    "Cirrosis hepática": "Liver cirrhosis",
    "Cáncer colorrectal": "Colorectal cancer",
    "Cáncer de bronquio y pulmón": "Bronchial and lung cancer",
    "Cáncer de cabeza y cuello": "Head and neck cancer",
    "Cáncer de cuello uterino": "Cervical cancer",
    "Cáncer de estómago": "Stomach cancer",
    "Cáncer de hueso y tejidos blandos": "Bone and soft tissue cancer",
    "Cáncer de hígado y vías biliares": "Liver and biliary tract cancer",
    "Cáncer de mama": "Breast cancer",
    "Cáncer de ovario": "Ovarian cancer",
    "Cáncer de próstata": "Prostate cancer",
    "Cáncer de páncreas": "Pancreatic cancer",
    "Cáncer de riñón y pelvis renal": "Kidney and renal pelvis cancer",
    "Cáncer de testículo": "Testicular cancer",
    "Cáncer de tiroides": "Thyroid cancer",
    "Cáncer de vejiga": "Bladder cancer",
    "Cáncer de útero": "Uterine cancer",
    "Cáncer inmunoproliferativo": "Immunoproliferative cancer",
    "Degeneración macular asociada a la edad": "Age-related macular degeneration",
    "Demencia": "Dementia",
    "Dependencia alcohol": "Alcohol dependence",
    "Dependencia otras sustancias": "Dependence on other substances",
    "Dependencia tabaco": "Tobacco dependence",
    "Dermatitis atópica": "Atopic dermatitis",
    "Diabetes": "Diabetes",
    "Discapacidad intelectual": "Intellectual disability",
    "Dislipemia": "Dyslipidemia",
    "EPOC": "COPD (Chronic Obstructive Pulmonary Disease)",
    "Enfermedad cerebrovascular mal definida y otra": "Ill-defined and other cerebrovascular disease",
    "Enfermedad de Hodgkin": "Hodgkin's disease",
    "Enfermedad de Parkinson": "Parkinson's disease",
    "Enfermedad del colágeno y vasculitis": "Collagen disease and vasculitis",
    "Enfermedad neurológica con déficit motor no ACV": "Neurological disease with motor deficit not stroke",
    "Enfermedad por reflujo gastroesofágico": "Gastroesophageal reflux disease",
    "Enfermedad valvular adquirida": "Acquired valvular disease",
    "Enteritis regional y colitis ulcerosa": "Regional enteritis and ulcerative colitis",
    "Epilepsia": "Epilepsy",
    "Esteatosis hepática": "Hepatic steatosis",
    "Fibrilación auricular": "Atrial fibrillation",
    "Fibromialgia": "Fibromyalgia",
    "Glaucoma": "Glaucoma",
    "Gota y otras artropatías por cristales": "Gout and other crystal arthropathies",
    "Hepatopatía crónica excepto cirrosis": "Chronic liver disease except cirrhosis",
    "Hipertensión": "Hypertension",
    "Hipotiroidismo": "Hypothyroidism",
    "Insuficiencia cardiaca": "Heart failure",
    "Insuficiencia renal crónica": "Chronic kidney failure",
    "Leucemia": "Leukemia",
    "Linfoma no Hodgkin": "Non-Hodgkin lymphoma",
    "Litiasis urinaria": "Urinary lithiasis",
    "Melanoma de piel": "Skin melanoma",
    "Obesidad": "Obesity",
    "Oclusión o estenosis arterias precerebrales": "Occlusion or stenosis of precerebral arteries",
    "Osteoporosis": "Osteoporosis",
    "Otra artropatía": "Other arthropathy",
    "Otro trastorno del desarrollo": "Other developmental disorder",
    "Otro trastorno funcional": "Other functional disorder",
    "Otro trastorno mental orgánico": "Other organic mental disorder",
    "Psoriasis": "Psoriasis",
    "Retinopatía": "Retinopathy",
    "Sarcoma de Kaposi": "Kaposi's sarcoma",
    "Secuela enfermedad cerebrovascular": "Sequelae of cerebrovascular disease",
    "Síndrome de malabsorción e intolerancia alimenticia": "Malabsorption syndrome and food intolerance",
    "Síndrome extrapiramidal": "Extrapyramidal syndrome",
    "Trastorno conducta alimentaria": "Eating disorder",
    "Trastorno de ansiedad": "Anxiety disorder",
    "Trastorno del espectro autista": "Autism spectrum disorder",
    "Trastorno esquizofrénico": "Schizophrenic disorder",
    "Trastorno estado animo": "Mood disorder",
    "Trastorno inicio infancia adolescencia": "Early childhood adolescence disorder",
    "Trastorno personalidad y comportamiento adulto": "Personality and adult behavior disorder",
    "VIH": "HIV",
}

dict_bps_english_group = {
    "hipertensión": "Hypertension",
    "Afecciones endocrinas": "Endocrine Conditions",
    "Afección osteomuscular": "Musculoskeletal Condition",
    "Afección respiratoria": "Respiratory Condition",
    "retinopatía": "Retinopathy",
    "trastorno_de_ansiedad": "Anxiety Disorder",
    "arteriopatía_de_extremidades": "Limb Arteriopathy",
    "Afecciones del sistema nervioso": "Nervous System Conditions",
    "Enfermedades de la piel": "Skin Diseases",
    "enfermedad_neurológica_con_déficit_motor_no_acv": "Neurological Disease with Motor Deficit not Stroke",
    "Salud mental": "Mental Health",
    "litiasis_urinaria": "Urinary Lithiasis",
    "insuficiencia_renal_crónica": "Chronic Kidney Failure",
    "cáncer_colorrectal": "Colorectal Cancer",
    "síndrome_extrapiramidal": "Extrapyramidal Syndrome",
    "gota_y_otras_artropatías_por_cristales": "Gout and other Crystal Arthropathies",
    "enfermedad_por_reflujo_gastroesofágico": "Gastroesophageal Reflux Disease",
    "glaucoma": "Glaucoma",
    "fibrilación_auricular": "Atrial Fibrillation",
    "cáncer_de_hueso_y_tejidos_blandos": "Bone and Soft Tissue Cancer",
    "cáncer_de_hígado_y_vías_biliares": "Liver and Biliary Tract Cancer",
    "cardiopatía_isquémica": "Ischemic Heart Disease",
    "cáncer_de_útero": "Uterine Cancer",
    "otro_trastorno_mental_orgánico": "Other Organic Mental Disorder",
    "enfermedad_del_colágeno_y_vasculitis": "Collagen Disease and Vasculitis",
    "degeneración_macular_asociada_a_la_edad": "Age-related Macular Degeneration",
    "Afección cardíaca": "Heart Condition",
    "cáncer_de_vejiga": "Bladder Cancer",
    "aneurisma_arterias_aorta__periféricas_y_viscerales": "Aneurysm of Aorta, Peripheral and Visceral Arteries",
    "demencia": "Dementia",
    "trastorno_esquizofrénico": "Schizophrenic Disorder",
    "enfermedad_de_parkinson": "Parkinson's Disease",
    "oclusión_o_estenosis_arterias_precerebrales": "Occlusion or Stenosis of Precerebral Arteries",
    "cáncer_de_mama": "Breast Cancer",
    "esteatosis_hepática": "Hepatic Steatosis",
    "cáncer_de_cabeza_y_cuello": "Head and Neck Cancer",
    "melanoma_de_piel": "Skin Melanoma",
    "síndrome_de_malabsorción_e_intolerancia_alimenticia": "Malabsorption Syndrome and Food Intolerance",
    "artritis_reumatoide_y_enfermedades_relacionadas": "Rheumatoid Arthritis and Related Diseases",
    "Neoplasias hematológicas": "Hematological Neoplasms",
    "cáncer_inmunoproliferativo": "Immunoproliferative Cancer",
    "dermatitis_atópica": "Atopic Dermatitis",
    "hepatopatía_crónica_excepto_cirrosis": "Chronic Liver Disease Except Cirrhosis",
    "arteriopatía_intraabdominal": "Intraabdominal Arteriopathy",
    "cáncer_de_páncreas": "Pancreatic Cancer",
    "cáncer_de_ovario": "Ovarian Cancer",
    "Afección del sistema digestivo": "Digestive System Condition",
    "cáncer_de_próstata": "Prostate Cancer",
    "cáncer_de_tiroides": "Thyroid Cancer",
    "anomalía_congénita_cardíaca_y_circulatoria": "Congenital Cardiac and Circulatory Anomaly",
    "enfermedad_de_hodgkin": "Hodgkin's Disease",
    "cáncer_de_bronquio_y_pulmón": "Bronchial and Lung Cancer",
    "cirrosis_hepática": "Liver Cirrhosis",
    "cáncer_de_cuello_uterino": "Cervical Cancer",
    "cáncer_de_riñón_y_pelvis_renal": "Kidney and Renal Pelvis Cancer",
    "cáncer_de_estómago": "Stomach Cancer",
    "Enfermedades infecciosas": "Infectious Diseases",
    "sarcoma_de_kaposi": "Kaposi's Sarcoma",
    "cáncer_de_testículo": "Testicular Cancer",
}
